### ISSUE TITLE
xrdp 0.9.15 on slackware 14.2 x86-64 doesn't compile

### ISSUE THREAD

**Issue by O-ring** [neutrinolabs/xrdp#1768]
Hello everyone,

xrdp 0.9.15 does not compile on slackware 14.2 (x86 64 bit). Here is the output. Let me know if you need any other information.

[configure --disable-pam --prefix=/usr --libdir=/usr/lib64]

make[3]: Entering directory '/tmp/XRDP/xrdp-0.9.15/sesman'
  CC       access.o
  CC       config.o
  CC       env.o
  CC       scp.o
  CC       scp_v0.o
  CC       scp_v1.o
  CC       scp_v1_mng.o
  CC       sesman.o
  CC       session.o
  CC       sig.o
  CC       xauth.o
  CC       verify_user.o
verify_user.c: In function 'auth_userpass':
verify_user.c:69:9: error: implicit declaration of function 'g_strncmp' [-Werror=implicit-function-declaration]
     if (g_strncmp(spw->pw_passwd, "x", 3) == 0)
         ^
verify_user.c: In function 'auth_change_pwd':
verify_user.c:220:26: error: implicit declaration of function 'g_strdup' [-Werror=implicit-function-declaration]
         spw->pw_passwd = g_strdup(hash);
                          ^
verify_user.c:220:24: error: assignment makes pointer from integer without a cast [-Werror=int-conversion]
         spw->pw_passwd = g_strdup(hash);
                        ^
verify_user.c:241:22: error: assignment makes pointer from integer without a cast [-Werror=int-conversion]
         stp->sp_pwdp = g_strdup(hash);
                      ^
verify_user.c: In function 'auth_crypt_pwd':
verify_user.c:292:5: error: implicit declaration of function 'g_strncpy' [-Werror=implicit-function-declaration]
     g_strncpy(crp, encr, 34);
     ^
cc1: all warnings being treated as errors
Makefile:652: recipe for target 'verify_user.o' failed
make[3]: *** [verify_user.o] Error 1
make[3]: Leaving directory '/tmp/XRDP/xrdp-0.9.15/sesman'
Makefile:706: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/tmp/XRDP/xrdp-0.9.15/sesman'
Makefile:483: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/tmp/XRDP/xrdp-0.9.15'
Makefile:415: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by matt335672** [comment]
Hi @O-ring 

Thanks for reporting this. Most platforms these days use PAM, and the CI testing assumes this will be used.

I'll check the other authentication modules are OK and make a proper PR for this. In the meantime, here's a patch you can apply to get you going:-

```diff
diff --git a/sesman/verify_user.c b/sesman/verify_user.c
index 175463ea..76918d68 100644
--- a/sesman/verify_user.c
+++ b/sesman/verify_user.c
@@ -29,6 +29,7 @@
 #endif
 
 #include "sesman.h"
+#include "string_calls.h"
 
 #include <stdio.h>
 #include <string.h>
```

You can use XRDP with PAM on Slackware now if that's of any interest - see #1558 for the details.

**Comment by O-ring** [comment]
Hello Matt,

thanks for the realtime response. Applied your fix & compiled. Everything is fine.
Thanks a lot.
I will close this ticket.
