### ISSUE TITLE
Xorg Drivers against xorg server 1.17.2 

### ISSUE THREAD

**Issue by fang64** [neutrinolabs/xrdp#298]
It seems I am unable to compile the master branch against xorg server 1.17.2 any ideas?

make[1]: Entering directory `/afs/uncc.edu/usr/s/rwilli95/linux/rpmbuild/BUILD/neutrinolabs-xrdp-ee89984/xorgxrdp'
Making all in module
make[2]: Entering directory `/afs/uncc.edu/usr/s/rwilli95/linux/rpmbuild/BUILD/neutrinolabs-xrdp-ee89984/xorgxrdp/module'
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..    -fvisibility=hidden -I/usr/include/xorg -I/usr/include/pixman-1 -I/usr/include/libdrm -I/usr/include/X11/dri   -I../../common -DSIMD_USE_ACCEL=1  -g -O2 -MT rdpDraw.lo -MD -MP -MF .deps/rdpDraw.Tpo -c -o rdpDraw.lo rdpDraw.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -fvisibility=hidden -I/usr/include/xorg -I/usr/include/pixman-1 -I/usr/include/libdrm -I/usr/include/X11/dri -I../../common -DSIMD_USE_ACCEL=1 -g -O2 -MT rdpDraw.lo -MD -MP -MF .deps/rdpDraw.Tpo -c rdpDraw.c  -fPIC -DPIC -o .libs/rdpDraw.o
rdpDraw.c: In function 'rdpDrawGetClip':
rdpDraw.c:69:20: error: 'struct _GC' has no member named 'clientClipType'
         switch (pGC->clientClipType)
                    ^
rdpDraw.c:80:27: error: 'struct _GC' has no member named 'clientClipType'
                        pGC->clientClipType));
                           ^
rdpDraw.c:51:43: note: in definition of macro 'LLOGLN'
     do { if (_level < LOG_LEVEL) { ErrorF _args ; ErrorF("\n"); } } while (0)
                                           ^
rdpDraw.c:114:28: error: 'struct _GC' has no member named 'clientClipType'
                 switch (pGC->clientClipType)
                            ^
rdpDraw.c:130:35: error: 'struct _GC' has no member named 'clientClipType'
                                pGC->clientClipType));
                                   ^
rdpDraw.c:51:43: note: in definition of macro 'LLOGLN'
     do { if (_level < LOG_LEVEL) { ErrorF _args ; ErrorF("\n"); } } while (0)
                                           ^
make[2]: *** [rdpDraw.lo] Error 1
make[2]: Leaving directory `/afs/uncc.edu/usr/s/rwilli95/linux/rpmbuild/BUILD/neutrinolabs-xrdp-ee89984/xorgxrdp/module'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/afs/uncc.edu/usr/s/rwilli95/linux/rpmbuild/BUILD/neutrinolabs-xrdp-ee89984/xorgxrdp'
make: *** [all] Error 2

**Comment by jsorg71** [comment]
I think this is fixed in devel branch.
Can you confirm?

**Comment by jsorg71** [comment]
I merged devel to master for xorgxrdp

**Comment by metalefty** [comment]
:+1: devel branch builds with 1.17.4 on FreeBSD.
It is not working (#299) but at least builds successfully.

**Comment by fang64** [comment]
@jsorg71 and @metalefty I can confirm the devel branch seemed to build under RHEL 7.2 which is when I ran into the problem. I'm not sure what changes solved that problem.

**Comment by fang64** [comment]
@jsorg71 I'll give the master branch a whirl again.

**Comment by metalefty** [comment]
Jay, you've merged devel into master but it seems xorgxrdp submodule still have hash 6edf9e5.
To fix the xorgxrdp build in master branch, I think xorgxrdp should be 3379d2c.

**Comment by vlaero** [comment]
+1 to metalefty's comment above.  This is preventing my from compiling the xorg module on EL 7.2.

**Comment by jsorg71** [comment]
Ok, done, thanks
