### ISSUE TITLE
Regression: who/utmp only shows the last XRDP user after display-string migration (ut_id collisions)

### ISSUE THREAD

**Issue by tsz8899** [neutrinolabs/xrdp#3751]
### Summary

After recent display-string changes, `who` on the server only shows the most recently logged-in XRDP user, instead of all concurrent XRDP sessions.

This appears to be a regression in `sesman/sesexec/sessionrecord.c` utmp ID generation.

---

### Environment

- xrdp branch: `devel`
- Reproduced after updates including:
  - `656a125c` (`utmp: Remove display number from interface`)
  - display string changes merged via PR #3729
- Linux with utmp enabled (`who` output affected)

---

### Previous behavior (before update)

Multiple concurrent XRDP users were visible in `who`, e.g.:

- `xrdp:60`
- `xrdp:61`
- `xrdp:62`

---

### Current behavior (after update)

Only one XRDP session (typically the last one) remains visible in `who`, e.g.:

- `xrdp:X11-88`

Even with multiple users connected, earlier entries are overwritten.

---

### Steps to reproduce

1. Start xrdp/sesman with current `devel`.
2. Connect multiple concurrent XRDP users.
3. Run `who` on server.
4. Observe only one XRDP user line remains (or lines overwrite each other).

---

### Root-cause analysis

In `sesman/sesexec/sessionrecord.c`, `get_display_num()` derives a numeric ID from display string for `ut_id`.

Current logic extracts the first digit run in the display string.
For displays like `X11-88`, `X11-89`, `X11-90`, this yields `11` for all sessions.

So all sessions get the same `ut_id` (e.g. `:%x` => `:b`), and `pututxline()` overwrites previous entries.

---

### Impact

- In multi-user scenarios, server-side tools can no longer reliably obtain the full logged-in user list.
- Session-name dependent applications can break (example: IME/input-method integrations that rely on session identity).
- Incorrect operational visibility (`who`, utmp-based auditing/monitoring).

---

### Suggested fix

For display strings like `x11-<num>` / `wayland-<num>`, derive utmp ID from the numeric part after `-` to avoid collisions.

(Alternative acceptable approach: any stable collision-resistant mapping of display string to `ut_id` constrained by field size.)

**Comment by tsz8899** [comment]
build failure:
~~~
  CC       eicp_process.o
eicp_process.c: In function ‘process_create_session_response’:
eicp_process.c:133:13: error: implicit declaration of function ‘strlcpy’; did you mean ‘strncpy’? [-Werror=implicit-function-declaration]
             strlcpy(s_item->display, display, sizeof(s_item->display));
             ^~~~~~~
             strncpy
cc1: all warnings being treated as errors
~~~

The build failure is introduced by commit c4727ad8 (Replace X11 display number with a display string).

  In sesman/eicp_process.c, this commit changed the display handling from int to const char * and added:

  strlcpy(s_item->display, display, sizeof(s_item->display));

  However, the file does not include string_calls.h, which declares strlcpy() in this project.
  With -Werror=implicit-function-declaration, this becomes a hard error:

  - implicit declaration of function 'strlcpy'
  - build stops at eicp_process.o

  So the root cause is: strlcpy() was introduced in eicp_process.c without adding its required header include.

**Comment by tsz8899** [comment]
XRDP sessions may be classified as tty instead of x11 after display-string changes, causing missing taskbar icons and pulseaudio-module-xrdp failure

  Context
  After recent XRDP display-string related updates, some desktop sessions show UI regressions.

  Observed Behavior

  - In failing sessions:
      - DISPLAY=:60
      - XDG_SESSION_TYPE=tty
      - Some applications do not show taskbar icons
      - pulseaudio-module-xrdp is not functioning correctly
  - In normal sessions:
      - DISPLAY=:60.0
      - XDG_SESSION_TYPE=x11
      - Taskbar icons display normally

  Relevant Code Change

  - Before commit c4727ad8:
      - sesman/sesexec/env.c explicitly set DISPLAY=:%d.0
  - After commit c4727ad8:
      - sesman/sesexec/session.c injects DISPLAY=:%d

  This DISPLAY format change is strongly correlated with downstream session-type detection differences (x11 vs tty) in the desktop startup path.

  Impact

  - Incorrect session typing in XRDP X11 sessions (tty instead of x11)
  - Desktop behavior regression (missing taskbar icons)
  - Audio integration regression (pulseaudio-module-xrdp ineffective)
  
  Validated Mitigation
  Setting XDG_SESSION_TYPE=x11 in startwm.sh consistently restores expected behavior:

  - correct session type (x11)
  - normal taskbar icon behavior
  - but pulseaudio-module-xrdp error

**Comment by matt335672** [comment]
Thanks for that comprehensive report @tsz8899. I'll get to this as soon as I can.

**Comment by tsz8899** [comment]
It has been fixed https://github.com/neutrinolabs/xrdp/pull/3753
