### ISSUE TITLE
compile error with xrdp version 0.9.18.1 on CentOS 7

### ISSUE THREAD

**Issue by jkeltz** [neutrinolabs/xrdp#2156]
I previously compiled xrdp with no error on CentOS 7.  I was using xrdp-0.9.16.  When updated to 0.9.18.1 I get this compile error:

```
guid.c: In function ‘guid_new’:
guid.c:36:12: error: missing braces around initializer [-Werror=missing-braces]
     struct guid guid = {0};
            ^
guid.c:36:12: error: (near initialization for ‘guid.g’) [-Werror=missing-braces]
cc1: all warnings being treated as errors
make[2]: *** [guid.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory `/tmp/xsys.19811.0/xrdp-0.9.18.1/common'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/tmp/xsys.19811.0/xrdp-0.9.18.1'
make: *** [all] Error 2
```

The solution was to replace "struct guid guid = {0};" line with "struct guid guid = {{0}};'"

It would be helpful to investigate whether this would work everywhere so that there could be a clean compile with older gcc.

**Comment by matt335672** [comment]
Hi @jkeltz 

Have a look at [this review comment](https://github.com/neutrinolabs/xrdp/pull/2011#commitcomment-63453607) and below.

Essentially the '{0}' (a universal zero initialiser) should be accepted by all C99-conforming compilers. I haven't checked for C90. Given there are only two years left in the RHEL 7 lifecycle, I'm not minded to really make an exception for this case.

**Comment by jkeltz** [comment]
No problem. That's fine.  I understand.  My auto build system patches it anyway, but I just figured if there was a way to make it compile on more platforms without any change, it's overall easier for everyone.
